[package]
name = "ractor_test"
version = "0.1.0"
edition = "2024"

[dependencies]
ractor = { version = "0.15.2", features = ["async-trait"] }
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"
tracing-glog = "0.4.0"
tracing-subscriber = "0.3.19"
tracing-test = "0.2.5"
