name: Rust CI

on:
  push:
    #branches:
    #  - main
  pull_request:
    #branches:
    #  - main

jobs:
  build:
    strategy:
      matrix:
        feature_async_trait: [true, false]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          override-with: rustup

      - name: Build
        run: cargo build --workspace --verbose ${{ matrix.feature_async_trait && '--features async-trait' || '' }}

      - name: Run tests
        run: cargo test --workspace --verbose ${{ matrix.feature_async_trait && '--features async-trait' || '' }}